### ISSUE TITLE
Exception 'yii\base\InvalidConfigException' with message 'Unsupported DB driver value'

### ISSUE THREAD

**Issue by northamerican** [AlexandreKilian/craft-react-demo#1]
When installing and following provided instructions, an error is given:

```
Stack trace:
#0 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\config\DbConfig->init()
#1 ~/Documents/craft-react-demo/vendor/craftcms/cms/src/services/Config.php(109): yii\base\BaseObject->__construct(Array)
#2 ~/Documents/craft-react-demo/vendor/craftcms/cms/src/services/Config.php(154): craft\services\Config->getConfigSettings('db')
#3 ~/Documents/craft-react-demo/vendor/craftcms/cms/src/helpers/App.php(286): craft\services\Config->getDb()
#4 ~/Documents/craft-react-demo/vendor/craftcms/cms/src/config/app.php(200): craft\helpers\App::dbConfig()
#5 [internal function]: {closure}()
#6 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/di/Container.php(503): call_user_func_array(Object(Closure), Array)
#7 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#8 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#9 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('db', true)
#10 ~/Documents/craft-react-demo/vendor/craftcms/cms/src/console/Application.php(146): yii\base\Module->get('db', true)
#11 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/di/Instance.php(164): craft\console\Application->get('db')
#12 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/di/Instance.php(137): yii\di\Instance->get(NULL)
#13 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/db/Migration.php(90): yii\di\Instance::ensure(Object(yii\di\Instance), 'yii\\db\\Connecti...')
#14 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\db\Migration->init()
#15 ~/Documents/craft-react-demo/vendor/craftcms/cms/src/console/controllers/InstallController.php(141): yii\base\BaseObject->__construct(Array)
#16 [internal function]: craft\console\controllers\InstallController->actionCraft()
#17 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#20 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#21 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
#22 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('install', Array)
#23 ~/Documents/craft-react-demo/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#24 ~/Documents/craft-react-demo/craft(22): yii\base\Application->run()
#25 {main}
```

**Comment by AlexandreKilian** [comment]
my bad, I put down the wrong command to install craft, `./craft install` doesnt write the config, it just installs the DB… try `./craft setup` instead, it'll ask you for your database config

**Comment by AlexandreKilian** [comment]
I updated the readme, it's correct now
